-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:14:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME NULL CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `update_at` DATETIME NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ---- UPDATE: HARA QUE SE ACTUALICE, CAMBIARA LA HORA DE LA ACTUALIZACION
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, -- BORRADO LOGICO - NO SE BORRA EL REGISTRO FISICAMENTE
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. BORRADO FISICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LOGICO (campo deleted activo -  deleted 1)
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `password_hash` VARCHAR(250) NOT NULL,
  `created_at` DATETIME NULL CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `update_at` DATETIME NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ---- UPDATE: HARA QUE SE ACTUALICE, CAMBIARA LA HORA DE LA ACTUALIZACION
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, -- BORRADO LOGICO - NO SE BORRA EL REGISTRO FISICAMENTE
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensaje` INT NOT NULL,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `update_at` DATETIME NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ---- UPDATE: HARA QUE SE ACTUALICE, CAMBIARA LA HORA DE LA ACTUALIZACION
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, -- BORRADO LOGICO - NO SE BORRA EL REGISTRO FISICAMENTE
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `update_at` DATETIME NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ---- UPDATE: HARA QUE SE ACTUALICE, CAMBIARA LA HORA DE LA ACTUALIZACION
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, -- BORRADO LOGICO - NO SE BORRA EL REGISTRO FISICAMENTE
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Insertar Datos en tablas
USE sistema_mensajes;
INSERT INTO usuarios(nombre_usuario) VALUES("Elisa")
INSERT INTO  roles(nombre_rol, descripcion_rol) VALUES ( "Admin", "Control total")
